In [6]:
# Python3.7
"""
HW5_4: Ch.2 Problem 3(a) of Fowler (2004
@author: Kiran Pandey
"""
import numpy as np
import math as m
import calc.euler_pole as euler

In [7]:
#+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
#                           Parameters
#+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
# radius of earth
R = 6371*1e5   
#latitude of point x on plate boundary in degrees
lat_x = (np.pi/180)*np.array([54,52,38,26,-13]) 
#longitude of point x on plate boundary in degrees
lon_x = (np.pi/180)*np.array([169,-169,-122,-110,-112])
#latitude of rotation pole P in degrees
lat_p = (np.pi/180)*np.array([48.7, 48.7,48.7, 48.7,55.6])
#longitude of rotation pole P in degrees
lon_p = (np.pi/180)*np.array([-78.2, -78.2,-78.2, -78.2,-90.1])
#angular velocity about rotaion pole
omega = 1e-7*np.array([7.5,7.5,7.5,7.5,13.6])

In [8]:
#+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
#                           Calculation
#+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
a = np.zeros(len(lat_x))
C = np.zeros(len(lat_x))
v = np.zeros(len(lat_x))
B = np.zeros(len(lat_x))
for i in range(len(lat_x)):
    # alpha in radian
    a[i] = euler.alpha(lat_p[i],lon_p[i],lat_x[i],lon_x[i])
    # C in radian
    C[i] = euler.C(lat_p[i],lon_p[i],lat_x[i],lon_x[i], a[i])
    # angular velociity in cm/yr
    v[i] = (np.pi/180)*euler.velocity(omega[i],a[i],R)
    #Azimuth of velocity vector with respect to north N
    B[i] = 1.5708+C[i]

In [9]:
#+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
#                           Output
#+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++   
a_deg  = 180/np.pi*a
print(a_deg)
C_deg  = 180/np.pi*C
print(C_deg)
B_deg  = 180/np.pi*B
print(B_deg)
v_CMperY = v
print(v_CMperY)

[62.77744783 54.10319414 33.08071339 33.54074944 71.02525191]
[43.17410965 54.55402335 56.81783314 39.00978957 12.87555152]
[133.17432011 144.55423381 146.8180436  129.01000003 102.87576198]
[ 7.41589311  6.75571166  4.55193063  4.60788925 14.30078264]
